const U = "https://usercontent.one/wp/www.michielsh.be/wp-content/uploads";

export const site = {
  name: "Zetormuseum",
  tagline: "Paradijs voor liefhebbers van landbouwmachines en oldtimertractoren",
  phone: "+32 475 65 26 36",
  phoneHref: "tel:+32475652636",
  email: "herman@hermanmichiels.be",
  emailHref: "mailto:herman@hermanmichiels.be",
  museumAddress: "Provinciebaan 3 — 2235 Houtvenne",
  companyAddress: "Koppenstraat 2 — 2221 Booischot",
  mapEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2507.889644609793!2d4.793970776291345!3d51.05512544364302!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c15af5fd5b2069%3A0x644d7a0bd17bf4d3!2sProvinciebaan%203%2C%202235%20Hulshout!5e0!3m2!1snl!2sbe!4v1715252661117!5m2!1snl!2sbe",
};

export const nav = [
  { href: "/", label: "Home" },
  { href: "/verhaal", label: "Verhaal" },
  { href: "/collectie", label: "Zetor-collectie" },
  { href: "/oldtimers", label: "Oldtimers" },
  { href: "/catalogus", label: "Catalogus" },
  { href: "/archief", label: "Archief" },
  { href: "/galerij", label: "Galerij" },
  { href: "/bezoek", label: "Bezoek" },
  { href: "/contact", label: "Contact" },
] as const;

/** Catalogusstukken — foto’s Desktop/1 + Desktop/2 + specificaties */
export const catalogEntries = [
  {
    id: "field-marshall",
    name: "Field Marshall",
    image: "/catalogus/field-marshall.png",
    year: "1952",
    origin: "Groot-Brittannië, Gainsborough",
    specs: [
      { label: "Bouwjaar", value: "1952" },
      { label: "Motor", value: "12/20 2-takt diesel gloeikop" },
      { label: "Boring × slag", value: "165 × 229 mm" },
      { label: "Cilinderinhoud", value: "4934 cm³" },
      { label: "Vermogen", value: "40 pk" },
      { label: "Transmissie", value: "3 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "2475 kg" },
      { label: "Oorsprong", value: "Groot-Brittannië, Gainsborough" },
    ],
  },
  {
    id: "pampa-t02",
    name: "Pampa T02",
    image: "/catalogus/pampa-t02.png",
    year: "1956",
    origin: "Argentinië",
    specs: [
      { label: "Bouwjaar", value: "1956" },
      { label: "Motor", value: "Pampa-gloeikop, tweetakt" },
      { label: "Boring × slag", value: "125 × 260 mm" },
      { label: "Cilinderinhoud", value: "1-cyl., 10.256 cm³" },
      { label: "Vermogen", value: "60 pk" },
      { label: "Transmissie", value: "2×3 vooruit, 2 achteruit" },
      { label: "Gewicht", value: "3500 kg" },
      { label: "Oorsprong", value: "Argentinië" },
    ],
  },
  {
    id: "vierzon-fv1",
    name: "Vierzon FV 1",
    image: "/catalogus/vierzon-fv1.png",
    year: "1947",
    origin: "Frankrijk",
    specs: [
      { label: "Bouwjaar", value: "1947" },
      { label: "Motor", value: "ééncyl. 2-takt gloeikop" },
      { label: "Boring × slag", value: "225 × 260 mm" },
      { label: "Cilinderinhoud", value: "10.320 cm³" },
      { label: "Vermogen", value: "45 pk" },
      { label: "Transmissie", value: "—" },
      { label: "Gewicht", value: "3300 kg" },
      { label: "Oorsprong", value: "Frankrijk" },
    ],
  },
  {
    id: "zetor-25",
    name: "Zetor 25",
    image: "/catalogus/zetor-25.png",
    year: "1946–1951",
    origin: "Tsjecho-Slowakije, Brno",
    specs: [
      { label: "Productie", value: "1946–1951 (serie tot 1961)" },
      { label: "Motor", value: "2-cil. watergekoelde diesel" },
      { label: "Boring × slag", value: "105 × 120 mm" },
      { label: "Cilinderinhoud", value: "2081 cm³" },
      { label: "Vermogen", value: "25 pk bij 1800 t/min" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "ca. 1750 kg" },
      { label: "PTO", value: "540 t/min" },
      { label: "Bijzonder", value: "Eerste massale Zetor; ~160.000 stuks in serie" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije, Brno" },
    ],
  },
  {
    id: "zetor-super-35",
    name: "Zetor Super 35",
    image: "/catalogus/zetor-super-35.png",
    year: "1955–1960",
    origin: "Tsjecho-Slowakije, Brno",
    specs: [
      { label: "Productie", value: "1955–1960" },
      { label: "Motor", value: "4-cil. diesel" },
      { label: "Boring × slag", value: "105 × 120 mm" },
      { label: "Cilinderinhoud", value: "4,2 L (4160 cm³)" },
      { label: "Vermogen", value: "42 pk bij 1500 t/min" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "2550 kg" },
      { label: "Banden", value: "6.00-20 / 13-28" },
      { label: "PTO", value: "live · 540 t/min" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije, Brno" },
    ],
  },
  {
    id: "hanomag-r27",
    name: "Hanomag R 27",
    image: "/catalogus/hanomag-r27.png",
    year: "1953–1957",
    origin: "Duitsland, Hannover",
    specs: [
      { label: "Productie", value: "1953–1957 · ca. 5962 stuks" },
      { label: "Motor", value: "Hanomag D21 · 3-cil. 4-takt diesel" },
      { label: "Boring × slag", value: "90 × 110 mm" },
      { label: "Cilinderinhoud", value: "2099 cm³" },
      { label: "Vermogen", value: "27 pk bij 1900 t/min" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit (opt. 10+2)" },
      { label: "Gewicht", value: "1585 kg" },
      { label: "Topsnelheid", value: "ca. 19,5 km/u" },
      { label: "Opvolger", value: "R 324 E (hernoemd 1957)" },
      { label: "Oorsprong", value: "Duitsland, Hannover" },
    ],
  },
  {
    id: "hanomag-r440",
    name: "Hanomag R 440",
    image: "/catalogus/hanomag-r440.png",
    year: "1957–1960",
    origin: "Duitsland (exportmodel)",
    specs: [
      { label: "Productie", value: "1957–1960 · ca. 5150 stuks" },
      { label: "Type", value: "Exportversie van R 435" },
      { label: "Motor", value: "Hanomag D28 · 4-cil. diesel" },
      { label: "Boring × slag", value: "90 × 110 mm" },
      { label: "Cilinderinhoud", value: "2799 cm³" },
      { label: "Vermogen", value: "35 pk DIN bij 1900 t/min" },
      { label: "Transmissie", value: "5/1 · opt. 10/2" },
      { label: "Gewicht", value: "ca. 1840 kg" },
      { label: "Hydrauliek", value: "optioneel · lift tot 1200 kg" },
      { label: "Oorsprong", value: "Duitsland (export)" },
    ],
  },
  {
    id: "allis-chalmers-d10",
    name: "Allis-Chalmers D10",
    image: "/catalogus/allis-chalmers-d10.png",
    year: "1959–1967",
    origin: "VS, West Allis (Wisconsin)",
    specs: [
      { label: "Productie", value: "1959–1967 · ca. 9100 stuks" },
      { label: "Motor", value: "4-cil. benzine Power-Crater" },
      { label: "Cilinderinhoud", value: "2,3–2,4 L (138,7 / 149 ci)" },
      { label: "Vermogen", value: "31 pk bij 1650 t/min" },
      { label: "PTO", value: "ca. 30 pk · 540 t/min" },
      { label: "Transmissie", value: "4 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "ca. 1225 kg (shipping)" },
      { label: "Wielbasis", value: "200 cm" },
      { label: "Kleur", value: "Persian Orange" },
      { label: "Oorsprong", value: "Verenigde Staten" },
    ],
  },
  {
    id: "same-da30",
    name: "SAME DA 30",
    image: "/catalogus/same-diesel.png",
    year: "1957–1961",
    origin: "Italië, Treviglio",
    specs: [
      { label: "Productie", value: "1957–1961" },
      { label: "Motor", value: "SAME DA 1102/C · 2-cil. luchtgekoeld diesel" },
      { label: "Boring × slag", value: "110 × 120 mm" },
      { label: "Cilinderinhoud", value: "2280 cm³" },
      { label: "Vermogen", value: "34 pk bij 2000 t/min" },
      { label: "Transmissie", value: "6 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "ca. 1650 kg (DT: 1805 kg)" },
      { label: "Topsnelheid", value: "ca. 24–25 km/u" },
      { label: "Bijzonder", value: "Luchtgekoelde diesel · DA = Diesel Aria" },
      { label: "Oorsprong", value: "Italië" },
    ],
  },
  {
    id: "zetor-super-50",
    name: "Zetor Super 50",
    image: "/catalogus/zetor-super-50.png",
    year: "1960–1968",
    origin: "Tsjecho-Slowakije, Brno",
    specs: [
      { label: "Productie", value: "1960–1968" },
      { label: "Motor", value: "4-cil. diesel" },
      { label: "Boring × slag", value: "105 × 120 mm" },
      { label: "Cilinderinhoud", value: "4,2 L (4160 cm³)" },
      { label: "Vermogen", value: "50 pk bij 1650 t/min" },
      { label: "Transmissie", value: "8+2 (ook 5/10-speed varianten)" },
      { label: "Gewicht", value: "ca. 2550 kg" },
      { label: "Brandstoftank", value: "ca. 68 L" },
      { label: "PTO", value: "live · 540 t/min" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije, Brno" },
    ],
  },
  {
    id: "zetor-15",
    name: "Zetor 15",
    image: "/catalogus/zetor-15.png",
    year: "1947–1949",
    origin: "Tsjecho-Slowakije, Brno",
    specs: [
      { label: "Productie", value: "1947–1949 · ca. 2215 stuks" },
      { label: "Motor", value: "1-cil. watergekoelde diesel" },
      { label: "Boring × slag", value: "120 × 140 mm" },
      { label: "Cilinderinhoud", value: "1,6 L (ca. 1583–1586 cm³)" },
      { label: "Vermogen", value: "15 pk bij 1500 t/min" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "ca. 1400 kg" },
      { label: "Wielbasis", value: "156 cm" },
      { label: "Bijzonder", value: "Zeldzaam vroeg Zetor-model" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije, Brno" },
    ],
  },
  {
    id: "zetor-6911",
    name: "Zetor 6911",
    image: "/catalogus/zetor-6911.png",
    year: "1977–1980",
    origin: "Tsjecho-Slowakije / Tsjechië",
    specs: [
      { label: "Productie", value: "1977–1980 · UR1 9-serie" },
      { label: "Motor", value: "Zetor Z6901 · 4-cil. diesel" },
      { label: "Boring × slag", value: "102 × 110 mm" },
      { label: "Cilinderinhoud", value: "3,6 L (3596 cm³)" },
      { label: "Vermogen", value: "65 pk bij 2200 t/min" },
      { label: "Transmissie", value: "10 vooruit, 2 achteruit" },
      { label: "Gewicht", value: "ca. 2950 kg" },
      { label: "Aandrijving", value: "2WD (6945 = 4WD-variant)" },
      { label: "PTO", value: "540 / 1000 t/min" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije" },
    ],
  },
  {
    id: "hanomag-r45",
    name: "Hanomag R 45",
    image: "/catalogus/hanomag-r45.png",
    year: "1950–1957",
    origin: "Duitsland, Hannover",
    specs: [
      { label: "Productie", value: "1950–1957 · ca. 8933 stuks" },
      { label: "Motor", value: "Hanomag D57 · 4-cil. diesel" },
      { label: "Boring × slag", value: "110 × 150 mm" },
      { label: "Cilinderinhoud", value: "5702 cm³" },
      { label: "Vermogen", value: "45 pk bij 1200 t/min" },
      { label: "Koppel", value: "ca. 280 Nm" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "ca. 3220–3420 kg" },
      { label: "Brandstoftank", value: "85 L" },
      { label: "Oorsprong", value: "Duitsland, Hannover" },
    ],
  },
  {
    id: "allis-chalmers-wd45",
    name: "Allis-Chalmers WD45",
    image: "/catalogus/allis-chalmers-wd45.png",
    year: "1953–1957",
    origin: "VS, West Allis (Wisconsin)",
    specs: [
      { label: "Productie", value: "1953–1957 · ca. 90.382 stuks" },
      { label: "Motor", value: "4-cil. benzine 3,7 L of 6-cil. diesel 3,8 L" },
      { label: "Vermogen", value: "ca. 45–48 pk (belt/PTO-klasse)" },
      { label: "Drawbar / belt", value: "getest ca. 39,5 / 44 pk" },
      { label: "Transmissie", value: "handgeschakeld · 2WD" },
      { label: "PTO", value: "live · 540 t/min" },
      { label: "Hitch", value: "Snap-Coupler" },
      { label: "Bijzonder", value: "Eerste Allis met stuurbekrachtiging" },
      { label: "Kleur", value: "Persian Orange" },
      { label: "Oorsprong", value: "Verenigde Staten" },
    ],
  },
  {
    id: "zetor-8911",
    name: "Zetor 8911",
    image: "/catalogus/zetor-8911.png",
    year: "jaren ’80 (Crystal)",
    origin: "Tsjecho-Slowakije",
    specs: [
      { label: "Serie", value: "Crystal / UR2-familie" },
      { label: "Motor", value: "4-cil. watergekoelde diesel (Crystal-lijn)" },
      { label: "Cilinderinhoud", value: "ca. 4,6 L (typisch Crystal)" },
      { label: "Vermogen", value: "ca. 80–90 pk-klasse" },
      { label: "Transmissie", value: "vaak 16+8 met powershift" },
      { label: "Aandrijving", value: "2WD (xx45 = 4WD-variant)" },
      { label: "PTO", value: "540 / 1000 t/min" },
      { label: "Cabine", value: "gesloten cabine (standaard op Crystal)" },
      { label: "Nota", value: "Specificaties o.b.v. verwante Crystal-modellen" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije" },
    ],
  },
  {
    id: "hanomag-r28",
    name: "Hanomag R 28",
    image: "/catalogus/hanomag-r28.png",
    year: "1951–1953",
    origin: "Duitsland, Hannover",
    specs: [
      { label: "Productie", value: "1951–1953 (S tot 1957)" },
      { label: "Motor", value: "Hanomag D28 · 4-cil. diesel" },
      { label: "Boring × slag", value: "90 × 110 mm" },
      { label: "Cilinderinhoud", value: "2799 cm³" },
      { label: "Vermogen", value: "28 pk bij ca. 1500 t/min" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "ca. 1740–1860 kg" },
      { label: "Topsnelheid", value: "ca. 18–19 km/u (opt. 25)" },
      { label: "Opvolger", value: "R 35 (1953)" },
      { label: "Oorsprong", value: "Duitsland, Hannover" },
    ],
  },
  {
    id: "hanomag-r35",
    name: "Hanomag R 35",
    image: "/catalogus/hanomag-r35.png",
    year: "1953–1957",
    origin: "Duitsland, Hannover",
    specs: [
      { label: "Productie", value: "1953–1957" },
      { label: "Motor", value: "Hanomag D28 · 4-cil. diesel" },
      { label: "Boring × slag", value: "90 × 110 mm" },
      { label: "Cilinderinhoud", value: "2799 cm³" },
      { label: "Vermogen", value: "35 pk (R 35/45: tot 45 pk met lader)" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit (opt. 10+2)" },
      { label: "Gewicht", value: "ca. 1860 kg (A-variant)" },
      { label: "Topsnelheid", value: "ca. 18–20 km/u" },
      { label: "Opvolger", value: "R 435 / R 440 (1957)" },
      { label: "Oorsprong", value: "Duitsland, Hannover" },
    ],
  },
  {
    id: "zetor-super-35-b",
    name: "Zetor Super 35",
    image: "/catalogus/zetor-super-35-b.png",
    year: "1955–1960",
    origin: "Tsjecho-Slowakije, Brno",
    specs: [
      { label: "Productie", value: "1955–1960" },
      { label: "Motor", value: "4-cil. diesel" },
      { label: "Boring × slag", value: "105 × 120 mm" },
      { label: "Cilinderinhoud", value: "4,2 L" },
      { label: "Vermogen", value: "42 pk bij 1500 t/min" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "2550 kg" },
      { label: "Banden", value: "6.00-20 / 13-28" },
      { label: "PTO", value: "live · 540 t/min" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije, Brno" },
    ],
  },
  {
    id: "zetor-super-50-b",
    name: "Zetor Super 50",
    image: "/catalogus/zetor-super-50-b.png",
    year: "1960–1968",
    origin: "Tsjecho-Slowakije, Brno",
    specs: [
      { label: "Productie", value: "1960–1968" },
      { label: "Motor", value: "4-cil. diesel" },
      { label: "Boring × slag", value: "105 × 120 mm" },
      { label: "Cilinderinhoud", value: "4,2 L" },
      { label: "Vermogen", value: "50 pk bij 1650 t/min" },
      { label: "Transmissie", value: "8+2" },
      { label: "Gewicht", value: "ca. 2550 kg" },
      { label: "PTO", value: "live · 540 t/min" },
      { label: "Plaat", value: "ZET·S·50" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije, Brno" },
    ],
  },
  {
    id: "zetor-15-b",
    name: "Zetor 15",
    image: "/catalogus/zetor-15-b.png",
    year: "1947–1949",
    origin: "Tsjecho-Slowakije, Brno",
    specs: [
      { label: "Productie", value: "1947–1949 · ca. 2215 stuks" },
      { label: "Motor", value: "1-cil. watergekoelde diesel" },
      { label: "Boring × slag", value: "120 × 140 mm" },
      { label: "Cilinderinhoud", value: "1,6 L" },
      { label: "Vermogen", value: "15 pk bij 1500 t/min" },
      { label: "Transmissie", value: "5 vooruit, 1 achteruit" },
      { label: "Gewicht", value: "ca. 1400 kg" },
      { label: "Bijzonder", value: "Vroeg en zeldzaam Zetor-model" },
      { label: "Oorsprong", value: "Tsjecho-Slowakije, Brno" },
    ],
  },
] as const;

/** Echte foto's van de museumhal (bron: michielsh.be) */
export const museumPhotos = [
  { src: `${U}/2024/05/M_1_1.jpg`, alt: "Museumhal met gerestaureerde Zetor-tractoren en emaille reclameborden", group: "hal" as const },
  { src: `${U}/2024/05/M_2_1.jpg`, alt: "Rode Zetor-tractoren op rij in de museumhal", group: "hal" as const },
  { src: `${U}/2024/05/M_3_1.jpg`, alt: "Zetor-collectie met vitrines en memorabilia", group: "hal" as const },
  { src: `${U}/2024/05/M_4_1.jpg`, alt: "Overzicht museumhal oldtimertractoren", group: "hal" as const },
  { src: `${U}/2024/05/M_5_1.jpg`, alt: "Gerestaureerde tractoren naast elkaar", group: "hal" as const },
  { src: `${U}/2024/05/M_6_1.jpg`, alt: "Detailopstelling in de Zetor-hal", group: "hal" as const },
  { src: `${U}/2024/05/M_7_1.jpg`, alt: "Museumcollectie landbouwmachines", group: "hal" as const },
  { src: `${U}/2024/05/M8_1a.jpg`, alt: "Oldtimertractoren in aparte museumhal", group: "oldtimer" as const },
  { src: `${U}/2024/05/M8_2a.jpg`, alt: "Internationale oldtimermerken in de collectie", group: "oldtimer" as const },
  { src: `${U}/2024/05/M8_3a.jpg`, alt: "Gerestaureerde classic tractoren", group: "oldtimer" as const },
  { src: `${U}/2024/05/oldtimer2.jpg`, alt: "Oldtimertractor — close-up", group: "oldtimer" as const },
  { src: `${U}/2024/05/oldtimer3.jpg`, alt: "Vintage tractor in museumopstelling", group: "oldtimer" as const },
  { src: `${U}/2024/05/oldtimer4.jpg`, alt: "Klassieke landbouwtractor", group: "oldtimer" as const },
  { src: `${U}/2024/05/oldtimer5.jpg`, alt: "Gerestaureerde oldtimer", group: "oldtimer" as const },
  { src: `${U}/2024/05/oldtimer6.jpg`, alt: "Historische tractor", group: "oldtimer" as const },
  { src: `${U}/2024/05/oldtimer7.jpg`, alt: "Collectorstractor", group: "oldtimer" as const },
  { src: `${U}/2024/05/oldtimer8.jpg`, alt: "Museumtractor detail", group: "oldtimer" as const },
  { src: `${U}/2024/06/123_1356.jpg`, alt: "Collectiestuk Zetor-museum", group: "detail" as const },
  { src: `${U}/2024/10/123_1448.jpg`, alt: "Tractor in de museumhal", group: "detail" as const },
  { src: `${U}/2024/10/123_1450.jpg`, alt: "Gerestaureerde Zetor", group: "detail" as const },
  { src: `${U}/2024/10/123_1451.jpg`, alt: "Zetor-detail in de collectie", group: "detail" as const },
  { src: `${U}/2024/10/123_1457.jpg`, alt: "Museumopstelling tractoren", group: "detail" as const },
  { src: `${U}/2024/10/DSC_1455.jpg`, alt: "Breed overzicht museumhal", group: "hal" as const },
  { src: `${U}/2024/10/123_7410.jpg`, alt: "Landbouwmachine in de collectie", group: "machines" as const },
  { src: `${U}/2024/10/123_7417.jpg`, alt: "Historisch landbouwwerktuig", group: "machines" as const },
  { src: `${U}/2024/10/123_7421.jpg`, alt: "Landbouwerfgoed Heist-op-den-Berg", group: "machines" as const },
  { src: `${U}/2024/10/123_7426.jpg`, alt: "Klassiek landbouwwerktuig", group: "machines" as const },
  { src: `${U}/2024/10/123_7431.jpg`, alt: "Museumstuk landbouwtechniek", group: "machines" as const },
  { src: `${U}/2024/10/123_7432.jpg`, alt: "Gerestaureerd werktuig", group: "machines" as const },
  { src: `${U}/2024/10/123_7445.jpg`, alt: "Collectie landbouwmachines", group: "machines" as const },
  { src: `${U}/2024/10/123_9766.jpg`, alt: "Zetor in detail", group: "detail" as const },
  { src: `${U}/2024/10/123_9776.jpg`, alt: "Rode Zetor close-up", group: "detail" as const },
  { src: `${U}/2024/10/123_9794.jpg`, alt: "Motor- en techniekdetail", group: "detail" as const },
  { src: `${U}/2024/10/123_9822.jpg`, alt: "Cabine en stuurhuis", group: "detail" as const },
  { src: `${U}/2024/10/123_9830.jpg`, alt: "Tractorfront Zetor", group: "detail" as const },
  { src: `${U}/2024/10/123_9894.jpg`, alt: "Museumtractor zijaanzicht", group: "detail" as const },
  { src: `${U}/2024/10/123_9906.jpg`, alt: "Collectiestuk in de hal", group: "detail" as const },
  { src: `${U}/2024/10/123_9917.jpg`, alt: "Gerestaureerde machine", group: "detail" as const },
  { src: `${U}/2024/10/123_9936.jpg`, alt: "Oldtimer in spotlight", group: "oldtimer" as const },
  { src: `${U}/2024/10/123_9957.jpg`, alt: "Historische tractor", group: "oldtimer" as const },
  { src: `${U}/2024/10/123_9965.jpg`, alt: "Museumopstelling", group: "hal" as const },
  { src: `${U}/2024/10/123_0023.jpg`, alt: "Zetor-collectie detail", group: "detail" as const },
  { src: `${U}/2024/10/123_0072.jpg`, alt: "Tractor in hangar", group: "hal" as const },
  { src: `${U}/2024/10/123_0148.jpg`, alt: "Collectieoverzicht", group: "hal" as const },
  { src: `${U}/2024/10/123_0179.jpg`, alt: "Museumhal sfeerbeeld", group: "hal" as const },
  { src: `${U}/2024/10/123_1354.jpg`, alt: "Zetor-reeks", group: "detail" as const },
  { src: `${U}/2024/10/123_1358.jpg`, alt: "Gerestaureerde Zetor", group: "detail" as const },
  { src: `${U}/2024/10/123_1375.jpg`, alt: "Collectiestuk", group: "detail" as const },
  { src: `${U}/2024/10/123_1376.jpg`, alt: "Museumtractor", group: "detail" as const },
  { src: `${U}/2024/10/123_1390.jpg`, alt: "Detailopname", group: "detail" as const },
  { src: `${U}/2024/10/123_1391.jpg`, alt: "Techniek en afwerking", group: "detail" as const },
  { src: `${U}/2024/10/456_4588.jpg`, alt: "Museumhal met tractoren", group: "hal" as const },
  { src: `${U}/2024/10/456_4594.jpg`, alt: "Rij oldtimers", group: "oldtimer" as const },
  { src: `${U}/2024/10/456_4595.jpg`, alt: "Collectieoverzicht oldtimers", group: "oldtimer" as const },
  { src: `${U}/2024/10/456_4598.jpg`, alt: "Museumopstelling merken", group: "oldtimer" as const },
];

export const zetorModels = [
  {
    name: "Zetor 25",
    era: "De oorsprong",
    text: "Van de vroegste legendes tot gerestaureerde schoonheden — de basis van Hermans levenslange passie voor het Tsjechische merk.",
  },
  {
    name: "Zetor Super 35 & 50",
    era: "Krachtlijnen",
    text: "Technisch én optisch puntgaaf gerestaureerd. Types die generaties landbouwers meenamen over de akkers.",
  },
  {
    name: "UR1-serie",
    era: "Universeel werkpaard",
    text: "De UR1-modelreeks vormt een kernstuk van de collectie — herkenbaar, robuust en zorgvuldig hersteld.",
  },
  {
    name: "Crystal-serie",
    era: "Iconische reeks",
    text: "De Crystal-modellen tonen hoe Zetor evolueerde: meer comfort, meer kracht, dezelfde karakteristieke uitstraling.",
  },
];

export const otherBrands = [
  { name: "Hanomag", note: "Start van het loonbedrijf in 1979 met een Hanomag Brillant 600 — vandaar de sterke Hanomag-lijn." },
  { name: "Lanz", note: "Duitse iconen, prachtig gerestaureerd in de aparte oldtimerhal." },
  { name: "Field Marshall", note: "Britse krachtpatsers naast de Zetor-collectie." },
  { name: "Landini", note: "Italiaanse classic in de internationale opstelling." },
  { name: "Pampa", note: "Zeldzamere verschijning in Belgische collecties." },
  { name: "Ursus", note: "Poolse verwanten van Zetor — ook aanwezig in museum én via URZET-Services." },
  { name: "Vierzon", note: "Franse oldtimertractoren, zij aan zij met de rest." },
  { name: "Balilla", note: "Historische Italiaanse tractoren in de collectie." },
  { name: "Favache", note: "Bijzondere stukken voor de echte kenner." },
  { name: "Fordson", note: "Klassiekers die de mechanisatie mee vormgaven." },
  { name: "Fahr", note: "Duitse landbouwtechniek, zorgvuldig gerestaureerd." },
];

export const expectItems = [
  {
    title: "Unieke Zetor-collectie",
    text: "Van Zetor 25 via Super 35/50 tot UR1 en Crystal — grotendeels technisch én optisch puntgaaf gerestaureerd. Een collectie die uniek is in de wereld.",
  },
  {
    title: "Aparte oldtimerhal",
    text: "Naast Zetor schitteren Hanomag, Lanz, Field Marshall, Landini, Pampa, Ursus, Vierzon, Balilla, Favache, Fordson, Fahr en meer.",
  },
  {
    title: "Archief & memorabilia",
    text: "Prospectussen, gebruikshandleidingen, wisselstukkenboeken, miniaturen, gadgets, zeldzame foto’s en kalenders — allemaal Zetor.",
  },
  {
    title: "Landbouwerfgoed regio",
    text: "Machines en werktuigen die het landbouwerfgoed rond Heist-op-den-Berg tot leven brengen.",
  },
  {
    title: "Sfeervolle museumhal",
    text: "Emaille reclameborden, vitrines en een hangarsfeer waar staal, lak en geschiedenis samenkomen.",
  },
  {
    title: "Begeleide groepsbezoeken",
    text: "Enkel op afspraak voor groepen — zo krijgt u de tijd en ruimte om alles rustig te ontdekken.",
  },
];

export const archiveItems = [
  { title: "Prospectussen", text: "Origineel drukwerk en foldercollectie van Zetor doorheen de jaren." },
  { title: "Gebruikshandleidingen", text: "Technische documentatie die onderhoud en bediening documenteert." },
  { title: "Wisselstukkenboeken", text: "Naslagwerken die onmisbaar zijn bij restauratie en herstellingen." },
  { title: "Miniaturen", text: "Schaalmodellen en collectorsitems in vitrines." },
  { title: "Gadgets", text: "Merchandising en kleine Zetor-schatten uit verschillende periodes." },
  { title: "Zeldzame foto’s", text: "Uniek beeldmateriaal van machines, mensen en momenten." },
  { title: "Kalenders", text: "Historische Zetor-kalenders als sfeervolle tijdscapsules." },
];
